name: Build and Release Container Image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          branch: main 
      
      - name: Extract version from release tag
        id: version
        run: |
          RAW_TAG=${{ github.event.release.tag_name }}
          CLEAN_TAG=${RAW_TAG#v}
          echo "VERSION=${CLEAN_TAG}" >> $GITHUB_ENV
          echo "Using version: $CLEAN_TAG"

      - name: Bump version number
        run: |
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml
          sed -i "s/version=\"[0-9]*\.[0-9]*\.[0-9]*\"/version=\"${VERSION}\"/" src/main.py

      - name: Apply version changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Bump version to ${VERSION}"
          branch: main
          file_pattern: |
            pyproject.toml
            src/main.py

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
